import { RouteInfo } from './sidebar.metadata';
export const ROUTES: RouteInfo[] = [
  {
    path: '',
    title: '-- HOME',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT","LAB-MANAGER","ENGINEER"]
  },
  {
    path: '/dashboard/main',
    title: 'Home',
    iconType: 'feather',
    icon: 'monitor',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT","LAB-MANAGER","ENGINEER"]
  },
  {
    path: '',
    title: '-- users managment',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT","LAB-MANAGER","ENGINEER"]
  },
  {
    path: 'dashboard/userRequest',
    title: 'Users Request',
    iconType: 'feather',
    icon: 'user-check',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN"]
  },
  {
    path: 'dashboard/userList',
    title: 'Users List',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT","LAB-MANAGER","ENGINEER"]
  },
  {
    path: 'dashboard/external',
    title: 'External users',
    iconType: 'feather',
    icon: 'user',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT"]
  },
  {
    path: 'dashboard/interns',
    title: 'Interns request',
    iconType: 'feather',
    icon: 'user',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT"]
  },
  {
    path: '',
    title: '-- internships managment',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ASSISTANT","ENGINEER","LAB-MANAGER","ADMIN"]
  },
  {
    path: '/dashboard/offer',
    title: 'Internship Offers',
    iconType: 'feather',
    icon: 'briefcase',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ASSISTANT","ENGINEER","LAB-MANAGER","ADMIN"]
  },
  {
    path: '/dashboard/selected-intern',
    title: 'Selected Interns',
    iconType: 'feather',
    icon: 'check-circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ENGINEER","LAB-MANAGER","ADMIN","ASSISTANT"]
  },
  {
    path: '/dashboard/interns-meeting-requests',
    title: 'Interns meeting requests',
    iconType: 'feather',
    icon: 'check-circle',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ENGINEER","LAB-MANAGER"]
  },
  {
    path: '',
    title: '-- equipment managment',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ASSISTANT","ADMIN"]
  },
  {
    path: '/dashboard/inventory',
    title: 'User equipments',
    iconType: 'feather',
    icon: 'package',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ASSISTANT","ADMIN"]
  },
  {
    path: '',
    title: '-- ressources managment',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ASSISTANT","ENGINEER","LAB-MANAGER"]
  },
  {
    path: '/dashboard/vehicle',
    title: 'Vehicles',
    iconType: 'feather',
    icon: 'truck',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ASSISTANT"]
  },
  {
    path: '/dashboard/room',
    title: 'Room Calendar',
    iconType: 'feather',
    icon: 'home',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ASSISTANT","ENGINEER","LAB-MANAGER"]
  },
  {
    path: '/dashboard/technician',
    title: 'Mission schedule',
    iconType: 'feather',
    icon: 'user-plus',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ASSISTANT","ENGINEER","LAB-MANAGER"]
  },
  {
    path: '',
    title: '-- lab env managment',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["LAB-MANAGER","ENGINEER"]
  },
  {
    path: '/dashboard/virt-env',
    title: 'Book a Lab',
    iconType: 'feather',
    icon: 'cloud',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["LAB-MANAGER","ENGINEER"]
  },
  {
    path: '/dashboard/myRequest',
    title: 'Booking list',
    iconType: 'feather',
    icon: 'download-cloud',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["LAB-MANAGER","ENGINEER"]
  },
  {
    path: '',
    title: '-- leave managment',
    iconType: '',
    icon: '',
    class: '',
    groupTitle: true,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT","LAB-MANAGER","ENGINEER"]
  },
  {
    path: '/dashboard/leave',
    title: 'Leave request',
    iconType: 'feather',
    icon: 'edit',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT","LAB-MANAGER","ENGINEER"]
  },
  {
    path: '/dashboard/myLeave',
    title: 'My leave requests',
    iconType: 'feather',
    icon: 'phone-off',
    class: '',
    groupTitle: false,
    badge: '',
    badgeClass: '',
    submenu: [],
    roles: ["ADMIN","ASSISTANT","LAB-MANAGER","ENGINEER"]
  },
  // {
  //   path: '',
  //   title: 'Users Managment',
  //   iconType: 'feather',
  //   icon: 'user',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   roles : [],
  //   submenu: [
  //     {
  //       path: 'dashboard/userRequest',
  //       title: 'Users Request',
  //       iconType: 'feather',
  //       icon: 'user-check',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []

  //     },
  //     {
  //       path: 'dashboard/userList',
  //       title: 'Users List',
  //       iconType: 'feather',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []
  //     },
  //   ],
  // },
  // {
  //   path: '',
  //   title: 'Resource Booking',
  //   iconType: 'feather',
  //   icon: 'calendar',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   roles : [],
  //   submenu: [
  //     {
  //       path: '/dashboard/vehicle',
  //       title: 'Vehicles',
  //       iconType: 'feather',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []

  //     },
  //     {
  //       path: '/dashboard/room',
  //       title: 'Rooms',
  //       iconType: 'feather',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []

  //     },
  //     {
  //       path: '/dashboard/technician',
  //       title: 'Technician',
  //       iconType: 'feather',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []

  //     },
  //   ],
  // },
  // {
  //   path: '',
  //   title: 'Labs management',
  //   iconType: 'feather',
  //   icon: 'cloud',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   roles : [ ],
  //   submenu: [
  //     {
  //       path: '/dashboard/virt-env',
  //       title: 'Book a Lab',
  //       iconType: 'feather',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []
  //     },
  //     {
  //       path: '/dashboard/myRequest',
  //       title: 'Booking list',
  //       iconType: 'feather',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []
  //     },
  //   ]
  // },
  // {
  //   path: '',
  //   title: 'personal leave',
  //   iconType: 'feather',
  //   icon: 'phone-off',
  //   class: 'menu-toggle',
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   roles : [ ],
  //   submenu: [
  //     {
  //       path: '/dashboard/leave',
  //       title: 'Leave request',
  //       iconType: 'feather',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []
  //     },
  //     {
  //       path: '/dashboard/myLeave',
  //       title: 'My leave requests',
  //       iconType: 'feather',
  //       icon: '',
  //       class: 'ml-menu',
  //       groupTitle: false,
  //       badge: '',
  //       badgeClass: '',
  //       submenu: [],
  //       roles : []
  //     },
  //   ]
  // }
];
